<?php

use App\Http\Controllers\Storefront\ArtworkController;
use App\Http\Controllers\Storefront\AccountController;
use App\Http\Controllers\Storefront\CartController;
use App\Http\Controllers\Storefront\CheckoutController;
use App\Http\Controllers\Storefront\CustomerAuthController;
use App\Http\Controllers\Storefront\HomeController;
use App\Http\Controllers\Storefront\InformationPageController;
use App\Http\Controllers\Storefront\ProductCategoryController;
use App\Http\Controllers\Storefront\ProductController;
use App\Http\Controllers\Storefront\SavedCharacterController;
use App\Http\Controllers\Storefront\ProductPreviewController;
use App\Http\Controllers\Storefront\SitemapController;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');
Route::middleware('guest')->group(function () {
    Route::get('/login', [CustomerAuthController::class, 'loginForm'])->name('login');
    Route::post('/login', [CustomerAuthController::class, 'login'])->middleware('throttle:10,1')->name('login.store');
    Route::get('/register', [CustomerAuthController::class, 'registerForm'])->name('register');
    Route::post('/register', [CustomerAuthController::class, 'register'])->middleware('throttle:10,1')->name('register.store');
});
Route::middleware('auth')->group(function () {
    Route::post('/logout', [CustomerAuthController::class, 'logout'])->name('logout');
    Route::get('/account', [AccountController::class, 'index'])->name('account.index');
    Route::get('/account/orders', [AccountController::class, 'orders'])->name('account.orders.index');
    Route::get('/account/orders/{orderNumber}', [AccountController::class, 'show'])->name('account.orders.show');
    Route::get('/account/orders/{orderNumber}/items/{item}/artwork', [AccountController::class, 'artwork'])->name('account.orders.artwork');
    Route::get('/account/characters', [SavedCharacterController::class, 'index'])->name('account.characters.index');
    Route::get('/account/characters/{character}/preview', [SavedCharacterController::class, 'preview'])->name('account.characters.preview');
    Route::delete('/account/characters/{character}', [SavedCharacterController::class, 'destroy'])->name('account.characters.destroy');
});
Route::get('/products', [ProductController::class, 'index'])->name('products.index');
Route::get('/products/{slug}', [ProductController::class, 'show'])->name('products.show');
Route::get('/admin-preview/products/{product}', ProductPreviewController::class)->name('admin.products.preview');
Route::get('/collections/{category:slug}', [ProductCategoryController::class, 'show'])->name('categories.show');
Route::get('/sitemap', [SitemapController::class, 'index'])->name('sitemap');
Route::get('/sitemap.xml', [SitemapController::class, 'xml'])->name('sitemap.xml');
Route::get('/terms-and-conditions', InformationPageController::class)->defaults('page', 'terms-and-conditions')->name('information.terms');
Route::get('/faq', InformationPageController::class)->defaults('page', 'faq')->name('information.faq');
Route::get('/delivery-shipping', InformationPageController::class)->defaults('page', 'delivery-shipping')->name('information.delivery');
Route::get('/returns-policy', InformationPageController::class)->defaults('page', 'returns-policy')->name('information.returns');
Route::get('/privacy-policy', InformationPageController::class)->defaults('page', 'privacy-policy')->name('information.privacy');
Route::get('/manage-cookies', InformationPageController::class)->defaults('page', 'manage-cookies')->name('information.cookies');
Route::get('/payment-methods', InformationPageController::class)->defaults('page', 'payment-methods')->name('information.payments');
Route::post('/products/{product:slug}/artwork', [ArtworkController::class, 'start'])->middleware('throttle:10,1')->name('artwork.start');
Route::get('/artwork/{publicId}', [ArtworkController::class, 'show'])->name('artwork.show');
Route::post('/artwork/{publicId}/upload', [ArtworkController::class, 'upload'])->middleware('throttle:30,1')->name('artwork.upload');
Route::get('/artwork/{publicId}/status', [ArtworkController::class, 'status'])->middleware('throttle:30,1')->name('artwork.status');
Route::get('/artwork/{publicId}/original', [ArtworkController::class, 'original'])->name('artwork.original');
Route::post('/artwork/{publicId}/cancel', [ArtworkController::class, 'cancel'])->middleware('throttle:10,1')->name('artwork.cancel');
Route::get('/artwork/{publicId}/assets/{asset}', [ArtworkController::class, 'asset'])->name('artwork.assets');
Route::get('/artwork/{publicId}/designs/{design}', [ArtworkController::class, 'design'])->name('artwork.designs');
Route::get('/artwork/{publicId}/designs/{design}/editor-background', [ArtworkController::class, 'designEditorBackground'])->name('artwork.design-editor-background');
Route::post('/artwork/{publicId}/designs/{design}/layout', [ArtworkController::class, 'designLayout'])->middleware('throttle:30,1')->name('artwork.design-layout');
Route::post('/artwork/{publicId}/variant', [ArtworkController::class, 'variant'])->name('artwork.variant');
Route::post('/artwork/{publicId}/name', [ArtworkController::class, 'name'])->middleware('throttle:60,1')->name('artwork.name');
Route::post('/artwork/{publicId}/regenerate', [ArtworkController::class, 'regenerate'])->middleware('throttle:5,1')->name('artwork.regenerate');
Route::post('/artwork/{publicId}/approve', [ArtworkController::class, 'approve'])->name('artwork.approve');
Route::post('/artwork/{publicId}/change', [ArtworkController::class, 'change'])->name('artwork.change');
Route::post('/artwork/{publicId}/save-character', [ArtworkController::class, 'saveCharacter'])->middleware('throttle:20,1')->name('artwork.save-character');
Route::post('/artwork/{publicId}/cart', [CartController::class, 'add'])->name('artwork.cart');
Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
Route::patch('/cart/items/{item}/quantity', [CartController::class, 'quantity'])->name('cart.quantity');
Route::delete('/cart/items/{item}', [CartController::class, 'remove'])->name('cart.remove');
Route::post('/cart/items/{item}/change-artwork', [CartController::class, 'changeArtwork'])->name('cart.change-artwork');
Route::get('/checkout', [CheckoutController::class, 'show'])->name('checkout.show');
Route::post('/checkout', [CheckoutController::class, 'store'])->name('checkout.store');
Route::get('/checkout/{orderNumber}/payment', [CheckoutController::class, 'payment'])->name('checkout.payment');
Route::post('/checkout/{orderNumber}/payment', [CheckoutController::class, 'pay'])->middleware('throttle:10,1')->name('checkout.pay');
Route::post('/checkout/{orderNumber}/payment/stripe-session', [CheckoutController::class, 'stripeSession'])->middleware('throttle:10,1')->name('checkout.stripe-session');
Route::post('/checkout/{orderNumber}/payment/stripe-status', [CheckoutController::class, 'stripeStatus'])->middleware('throttle:60,1')->name('checkout.stripe-status');
Route::get('/checkout/{orderNumber}/payment/stripe-return', [CheckoutController::class, 'stripeReturn'])->name('checkout.stripe-return');
Route::get('/orders/{orderNumber}/confirmation', [CheckoutController::class, 'confirmation'])->name('orders.confirmation');
