<?php

return [
    'suppliers' => [
        'prodigi' => [
            '650ML-WATER-BOTTLE' => [
                'source_directory' => 'product-assets/prodigi/650ML-WATER-BOTTLE',
                'assets' => [
                    'product-01' => [
                        'filename' => 'Prodigi-copper-water-bottle01.jpg',
                        'role' => 'primary',
                        'variant_options' => ['colour' => 'white'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/cattie-water-bottle/catalogue/bottle01.jpg'],
                        'alt_text' => 'White 650 ml Kattie water bottle with colourful wraparound artwork and lid beside it',
                        'sort_order' => 0,
                    ],
                    'product-02' => [
                        'filename' => 'Prodigi-copper-water-bottle02.jpg',
                        'role' => 'gallery',
                        'variant_options' => ['colour' => 'navy'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/cattie-water-bottle/catalogue/bottle02.jpg'],
                        'alt_text' => 'Navy 650 ml Kattie water bottle with copper-coloured character artwork',
                        'sort_order' => 1,
                    ],
                    'close-up' => [
                        'filename' => 'Prodigi-copper-water-bottle-close-up.jpg',
                        'role' => 'detail',
                        'variant_options' => ['colour' => 'white'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/cattie-water-bottle/catalogue/close-up.jpg'],
                        'alt_text' => 'Close-up of the printed artwork finish on the white Kattie water bottle',
                        'sort_order' => 2,
                    ],
                    'lid' => [
                        'filename' => 'Prodigi-copper-water-bottle-lid.jpg',
                        'role' => 'detail',
                        'variant_options' => ['colour' => 'white'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/cattie-water-bottle/catalogue/lid.jpg'],
                        'alt_text' => 'Close-up of the stainless-steel carry lid on the white Kattie water bottle',
                        'sort_order' => 3,
                    ],
                    'blank' => [
                        'filename' => 'Prodigi-copper-water-bottle-blank.jpg',
                        'role' => 'mockup_source',
                        'variant_options' => ['colour' => 'white'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/cattie-water-bottle/mockup/blank.jpg'],
                    ],
                ],
            ],
        ],
        'treatpod' => [
            'STATIONERY-PENCIL-TIN' => [
                'source_directory' => 'product-assets/treatpod/STATIONERY-PENCIL-TIN',
                'assets' => [
                    'blue-primary' => [
                        'filename' => 'substationerytin-blub.jpg',
                        'role' => 'primary',
                        'variant_options' => ['colour' => 'blue'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/personalised-stationery-pencil-tin/supplier/blue/substationerytin-blub.jpg'],
                        'alt_text' => 'Blue stationery and pencil tin with a white glossy printable insert',
                        'sort_order' => 0,
                    ],
                    'blue-gallery' => [
                        'filename' => 'substationerytin-blum.jpg',
                        'role' => 'gallery',
                        'variant_options' => ['colour' => 'blue'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/personalised-stationery-pencil-tin/supplier/blue/substationerytin-blum.jpg'],
                        'alt_text' => 'Blue pencil tin displaying an example printed insert design',
                        'sort_order' => 1,
                    ],
                    'pink-primary' => [
                        'filename' => 'substationerytin-pnkb.jpg',
                        'role' => 'primary',
                        'variant_options' => ['colour' => 'pink'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/personalised-stationery-pencil-tin/supplier/pink/substationerytin-pnkb.jpg'],
                        'alt_text' => 'Pink stationery and pencil tin with a white glossy printable insert',
                        'sort_order' => 100,
                    ],
                    'pink-gallery' => [
                        'filename' => 'substationerytin-pnkm.jpg',
                        'role' => 'gallery',
                        'variant_options' => ['colour' => 'pink'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/personalised-stationery-pencil-tin/supplier/pink/substationerytin-pnkm.jpg'],
                        'alt_text' => 'Pink pencil tin displaying an example printed insert design',
                        'sort_order' => 101,
                    ],
                    'silver-primary' => [
                        'filename' => 'substationerytinb.jpg',
                        'role' => 'primary',
                        'variant_options' => ['colour' => 'silver'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/personalised-stationery-pencil-tin/supplier/silver/substationerytinb.jpg'],
                        'alt_text' => 'Silver stationery and pencil tin with a white glossy printable insert',
                        'sort_order' => 200,
                    ],
                    'silver-gallery' => [
                        'filename' => 'substationerytinmockm.jpg',
                        'role' => 'gallery',
                        'variant_options' => ['colour' => 'silver'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/personalised-stationery-pencil-tin/supplier/silver/substationerytinmockm.jpg'],
                        'alt_text' => 'Silver pencil tin displaying an example printed insert design',
                        'sort_order' => 201,
                    ],
                ],
            ],
            'LUNCHBOX-SMALL' => [
                'source_directory' => 'product-assets/treatpod/LUNCHBOX-SMALL',
                'assets' => [
                    'blue-primary' => [
                        'filename' => 'lunchbox-blue.jpg',
                        'role' => 'primary',
                        'variant_options' => ['colour' => 'blue'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/small-plastic-lunchbox/supplier/blue/lunchbox-blue.jpg'],
                        'alt_text' => 'Blue small plastic lunchbox with a white printable lid',
                        'sort_order' => 0,
                    ],
                    'pink-primary' => [
                        'filename' => 'lunchbox-pink.jpg',
                        'role' => 'primary',
                        'variant_options' => ['colour' => 'pink'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/small-plastic-lunchbox/supplier/pink/lunchbox-pink.jpg'],
                        'alt_text' => 'Pink small plastic lunchbox with a white printable lid',
                        'sort_order' => 100,
                    ],
                    'pink-gallery' => [
                        'filename' => 'pink-plastic-lunch-box-design.png',
                        'role' => 'gallery',
                        'variant_options' => ['colour' => 'pink'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/small-plastic-lunchbox/supplier/pink/pink-plastic-lunch-box-design.png'],
                        'alt_text' => 'Pink small lunchbox displaying an example printed lid design',
                        'sort_order' => 101,
                    ],
                    'white-primary' => [
                        'filename' => 'lunchbox-wht.jpg',
                        'role' => 'primary',
                        'variant_options' => ['colour' => 'white'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/small-plastic-lunchbox/supplier/white/lunchbox-wht.jpg'],
                        'alt_text' => 'White small plastic lunchbox with a printable lid',
                        'sort_order' => 200,
                    ],
                    'white-gallery' => [
                        'filename' => 'white-plastic-lunch-box-design.png',
                        'role' => 'gallery',
                        'variant_options' => ['colour' => 'white'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/small-plastic-lunchbox/supplier/white/white-plastic-lunch-box-design.png'],
                        'alt_text' => 'White small lunchbox displaying an example printed lid design',
                        'sort_order' => 201,
                    ],
                ],
            ],
            'WB-750ML-FLIP' => [
                'source_directory' => 'product-assets/treatpod/WB-750ML-FLIP',
                'assets' => [
                    'white-primary' => [
                        'filename' => 'wb-750mlwht-flipred.jpg',
                        'role' => 'primary',
                        'variant_options' => ['colour' => 'white'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/water-bottle-with-red-flip-lid/catalogue/wb-750mlwht-flipred.jpg'],
                        'alt_text' => 'White 750 ml aluminium water bottle with a red flip lid',
                        'sort_order' => 0,
                    ],
                    'white-gallery' => [
                        'filename' => 'wb-750mlwht-flipredm.jpg',
                        'role' => 'gallery',
                        'variant_options' => ['colour' => 'white'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/water-bottle-with-red-flip-lid/catalogue/wb-750mlwht-flipredm.jpg'],
                        'alt_text' => 'White bottle displaying an example wraparound printed design',
                        'sort_order' => 1,
                    ],
                    'silver-primary' => [
                        'filename' => 'wb-750mlslv-flipred.jpg',
                        'role' => 'primary',
                        'variant_options' => ['colour' => 'silver'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/water-bottle-with-red-flip-lid/catalogue/wb-750mlslv-flipred.jpg'],
                        'alt_text' => 'Silver 750 ml aluminium water bottle with a red flip lid',
                        'sort_order' => 10,
                    ],
                    'silver-gallery' => [
                        'filename' => 'wb-750mlslv-flipredm.jpg',
                        'role' => 'gallery',
                        'variant_options' => ['colour' => 'silver'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/water-bottle-with-red-flip-lid/catalogue/wb-750mlslv-flipredm.jpg'],
                        'alt_text' => 'Silver bottle displaying an example printed design',
                        'sort_order' => 11,
                    ],
                    'silver-detail' => [
                        'filename' => 'wb-750mlslv-flipred-1a0f7e95-6a87-46c6-9c05-02ef967ee1ac.jpg',
                        'role' => 'detail',
                        'variant_options' => ['colour' => 'silver'],
                        'public' => ['disk' => 'public', 'storage_key' => 'products/water-bottle-with-red-flip-lid/catalogue/wb-750mlslv-flipred-1a0f7e95-6a87-46c6-9c05-02ef967ee1ac.jpg'],
                        'alt_text' => 'Example showing how bold artwork appears on the silver bottle finish',
                        'sort_order' => 12,
                    ],
                ],
            ],
        ],
    ],
];
