<x-layouts.storefront :title="$product->name.' | Cattie.uk'" :description="$product->meta_description" :canonical="route('products.show',$product->slug)">
@php($processing=$session && in_array($session->status->value, ['preparing_photo','generating']))
@php($editing=$session && $session->status->value==='awaiting_upload')
@php($savedPersonalisation=collect($session?->personalisation_snapshot??[])->keyBy('key'))
@php($editingPreview=$editing?$session->currentGeneration?->assets?->firstWhere('kind','web_preview'):null)
@if(!$session || $processing || $editing)
<section class="shell py-12" x-data="{variant:@js($editing?$session->product_variant_id:$defaultVariant?->id),style:@js($editing?$session->artwork_style_id:$recommendedStyle?->id),selectedImage:@js($defaultImage?->id),removeExistingPhoto:false,hasExistingPhoto:@js((bool)$editingPreview),newPhotoSelected:false,nameValue:@js(old('personalisation.name',$savedPersonalisation->get('name')['value']??'')),images:@js($product->images->map(fn($image)=>['id'=>$image->id,'variant_id'=>$image->product_variant_id])->values()),photoReady(){return(this.hasExistingPhoto&&!this.removeExistingPhoto)||this.newPhotoSelected},selectVariant(id){this.variant=id;@unless($product->designTemplate)this.selectedImage=this.images.find(image=>image.variant_id===id)?.id??null;@endunless}}"><div class="grid gap-12 lg:grid-cols-2 lg:gap-20">
<div>
<div class="aspect-square overflow-hidden rounded-[2.5rem] bg-sand">
@foreach($product->images as $image)<img x-show="selectedImage===@js($image->id)" src="{{ $image->url() }}" alt="{{ $image->alt_text }}" class="h-full w-full object-contain" @if(!$image->is($defaultImage)) style="display:none" @endif>@endforeach
<div x-show="!selectedImage" class="flex h-full items-center justify-center p-10 text-center text-muted" style="display:none">Official photography for this colour is not available yet.</div>
</div>
@if($product->images->count()>1)@if($product->designTemplate)<div class="mt-4"><p class="text-sm font-bold text-ink">Bottle examples</p><p class="mt-1 text-xs text-muted">Official Prodigi product photography. These are not personalised mockups.</p></div>@endif<div class="mt-3 grid min-h-24 grid-cols-4 content-start gap-3">@foreach($product->images as $image)<button @unless($product->designTemplate)x-show="variant===@js($image->product_variant_id)"@endunless @click="selectedImage=@js($image->id)" type="button" class="aspect-square cursor-pointer overflow-hidden rounded-xl bg-sand ring-2 ring-transparent" :class="selectedImage===@js($image->id)?'ring-coral':''" @if(!$product->designTemplate && $image->product_variant_id!==$defaultVariant?->id) style="display:none" @endif><img src="{{ $image->url() }}" alt="" class="h-full w-full object-cover"></button>@endforeach</div>@else<div class="mt-3 min-h-24" aria-hidden="true"></div>@endif
</div>
<div><p class="eyebrow">Made just for them</p><h1 class="mt-4 font-display text-5xl">{{ $product->name }}</h1><p class="mt-5 text-lg leading-8 text-muted">{{ $product->short_description }}</p><p class="mt-6 text-2xl font-bold">From {{ $product->formattedPrice() }}</p>
<form action="{{ $editing ? route('artwork.upload',$session->public_id) : route('artwork.start',$product->slug) }}" method="POST" enctype="multipart/form-data">@csrf
<fieldset class="mt-9"><legend class="font-display text-xl">{{ $product->designTemplate ? 'Bottle colour' : 'Choose your option' }}</legend><div class="mt-4 {{ $product->designTemplate ? 'bottle-colour-options grid grid-cols-4 gap-2' : 'flex flex-wrap gap-3' }}">@foreach($product->variants as $variant)<label class="selection-card min-w-0"><input class="sr-only" type="radio" name="variant_id" value="{{ $variant->id }}" x-model="variant" @change="selectVariant(@js($variant->id))" required><span>{{ $variant->name }}<small>{{ $variant->formattedPrice() }}</small></span></label>@endforeach</div></fieldset>
@if($product->designTemplate)<input type="hidden" name="artwork_style_id" value="{{ $editing?$session->artwork_style_id:$recommendedStyle?->id }}">@else
<fieldset class="mt-10"><legend class="font-display text-xl">Choose your artwork style</legend><div class="mt-4 grid gap-3 sm:grid-cols-2">@foreach($product->artworkStyles as $style)<label class="style-card"><input class="sr-only" type="radio" name="artwork_style_id" value="{{ $style->id }}" x-model="style" required><span class="flex justify-between"><strong>{{ $style->name }}</strong>@if($style->is($recommendedStyle))<small>Recommended</small>@endif</span><small class="mt-2 block text-muted">{{ $style->description }}</small></label>@endforeach</div></fieldset>
@endif
@if($product->personalisationFields->isNotEmpty())<fieldset class="mt-10"><legend class="font-display text-xl">A few personal touches</legend><div class="mt-5 space-y-5">@foreach($product->personalisationFields as $field)@php($savedValue=old('personalisation.'.$field->key,$savedPersonalisation->get($field->key)['value']??''))<div><div class="flex items-center justify-between gap-3"><label class="form-label" for="field-{{ $field->id }}">{{ $field->label }} @unless($field->is_required)<span class="font-normal text-muted">(optional)</span>@endunless</label>@if($field->key==='name')<span class="text-xs text-muted" x-text="Math.max(0, {{ $field->validation_rules['max']??12 }} - nameValue.length) + ' characters left'"></span>@endif</div>@switch($field->type->value)@case('textarea')<textarea class="form-control" id="field-{{ $field->id }}" name="personalisation[{{ $field->key }}]" rows="3" @if($field->key==='name') x-model="nameValue" @endif @required($field->is_required) maxlength="{{ $field->validation_rules['max']??500 }}">{{ $savedValue }}</textarea>@break @case('select')<select class="form-control" id="field-{{ $field->id }}" name="personalisation[{{ $field->key }}]" @if($field->key==='name') x-model="nameValue" @endif @required($field->is_required)><option value="">Choose an option</option>@foreach($field->configuration['options']??[] as $option)<option @selected($savedValue===$option)>{{ $option }}</option>@endforeach</select>@break @case('date')<input class="form-control" id="field-{{ $field->id }}" name="personalisation[{{ $field->key }}]" type="date" value="{{ $savedValue }}" @if($field->key==='name') x-model="nameValue" @endif @required($field->is_required)>@break @default<input class="form-control" id="field-{{ $field->id }}" name="personalisation[{{ $field->key }}]" value="{{ $savedValue }}" @if($field->key==='name') x-model="nameValue" @endif @required($field->is_required) maxlength="{{ $field->validation_rules['max']??255 }}">@endswitch</div>@endforeach</div></fieldset>@endif
<fieldset class="mt-10"><legend class="font-display text-xl">Upload photo</legend>@if($editing && $editingPreview)<div x-show="!removeExistingPhoto" class="relative mt-4 h-28 w-28"><img src="{{ route('artwork.assets',[$session->public_id,$editingPreview]) }}" alt="Your AI illustration" class="h-full w-full rounded-2xl object-cover shadow"><button type="button" @click="removeExistingPhoto=true;newPhotoSelected=false" class="absolute -right-2 -top-2 flex h-7 w-7 items-center justify-center rounded-full bg-ink text-lg leading-none text-white shadow" aria-label="Remove selected photo">×</button></div>@endif<label x-show="{{ $editing && $editingPreview ? 'removeExistingPhoto' : 'true' }}" class="mt-4 flex cursor-pointer flex-col rounded-2xl border-2 border-dashed border-coral/40 bg-white p-6"><span class="font-bold">Choose a favourite photo</span><span class="mt-1 text-sm text-muted">JPEG, PNG or WebP · up to 10 MB</span><input class="mt-4 block max-w-full" type="file" name="photo" accept="image/jpeg,image/png,image/webp" @change="newPhotoSelected=$event.target.files.length>0" @required(!$editing || !$editingPreview)></label></fieldset>
@if($errors->any())<div class="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
<div class="mt-10 rounded-3xl bg-white p-6 shadow-sm"><button class="button-primary w-full disabled:cursor-not-allowed disabled:opacity-50" type="submit" @if($product->designTemplate) :disabled="!photoReady() || !nameValue.trim()" @endif>Preview</button><p class="mt-3 text-center text-xs text-muted">We’ll prepare your personalised design.</p></div></form>
<div class="mt-10 border-t border-rose/25 pt-8"><h2 class="font-display text-2xl">About your gift</h2><p class="mt-4 leading-7 text-muted">{{ $product->description }}</p></div>
@include('storefront.products._shipping-returns')
</div></div></section>
@endif
@if($session && !$editing)
@include('storefront.artwork._workspace', ['session' => $session])
@endif
@include('storefront.products._related', ['relatedProducts' => $relatedProducts])
</x-layouts.storefront>
