<x-layouts.storefront :title="$product->meta_title ?: $product->name.' | Kattie.uk'" :description="$product->meta_description" :canonical="isset($previewRobots) ? null : route('products.show',$product->slug)" :robots="$previewRobots ?? null">
<nav class="shell pt-8 text-sm text-muted" aria-label="Breadcrumb"><ol class="flex flex-wrap items-center gap-2"><li><a class="hover:text-coral" href="{{ route('home') }}">Home</a></li><li aria-hidden="true">→</li><li><a class="hover:text-coral" href="{{ route('products.index') }}">Shop</a></li><li aria-hidden="true">→</li><li aria-current="page">{{ $product->name }}</li></ol></nav>
@php($processing=$session && in_array($session->status->value, ['preparing_photo','generating']))
@php($editing=$session && $session->status->value==='awaiting_upload')
@php($savedPersonalisation=collect($session?->personalisation_snapshot??[])->keyBy('key'))
@php($editingPreview=$editing?$session->currentGeneration?->assets?->firstWhere('kind','web_preview'):null)
@php($hasVariantImages=$product->images->contains(fn($image)=>(bool)$image->product_variant_id))
@php($availableVariantIds=$product->variants->filter(fn($variant)=>!$product->designTemplate||$variant->hasSingleActiveFulfilmentMapping())->pluck('id')->values())
@if(!$session || $processing || $editing)
<section class="shell py-4 lg:py-12" x-data="{variant:@js($editing?$session->product_variant_id:$defaultVariant?->id),availableVariantIds:@js($availableVariantIds),style:@js($editing?$session->artwork_style_id:$recommendedStyle?->id),selectedImage:@js($defaultImage?->id),hasVariantImages:@js($hasVariantImages),removeExistingPhoto:false,hasExistingPhoto:@js((bool)$editingPreview),newPhotoSelected:false,uploadPreview:null,nameValue:@js(old('personalisation.name',$savedPersonalisation->get('name')['value']??'')),submitting:false,images:@js($product->images->map(fn($image)=>['id'=>$image->id,'variant_id'=>$image->product_variant_id])->values()),photoReady(){return(this.hasExistingPhoto&&!this.removeExistingPhoto)||this.newPhotoSelected},variantReady(){return this.availableVariantIds.includes(this.variant)},selectPhoto(event){if(this.uploadPreview)URL.revokeObjectURL(this.uploadPreview);const file=event.target.files[0];this.newPhotoSelected=Boolean(file);this.uploadPreview=file?URL.createObjectURL(file):null},imageVisible(image){return !this.hasVariantImages||image.variant_id===this.variant},selectVariant(id){this.variant=id;if(this.hasVariantImages)this.selectedImage=this.images.find(image=>image.variant_id===id)?.id??null}}"><div class="grid min-w-0 [&>*]:min-w-0 lg:grid-cols-2 lg:gap-20">
<div class="min-w-0 lg:sticky lg:top-24 lg:self-start">
<div class="aspect-square overflow-hidden">
@foreach($product->images as $image)<img x-show="selectedImage===@js($image->id)" src="{{ $image->url() }}" alt="{{ $image->alt_text }}" class="h-full w-full object-cover" @if(!$image->is($defaultImage)) style="display:none" @endif>@endforeach
<div x-show="!selectedImage" class="flex h-full items-center justify-center p-10 text-center text-muted" style="display:none">Official photography for this colour is not available yet.</div>
</div>
@if($product->images->count()>1)<div class="mt-3 grid min-h-24 grid-cols-4 content-start gap-3">@foreach($product->images as $image)<button x-show="imageVisible({id:@js($image->id),variant_id:@js($image->product_variant_id)})" @click="selectedImage=@js($image->id)" type="button" class="aspect-square cursor-pointer overflow-hidden rounded-xl bg-sand ring-2 ring-transparent" :class="selectedImage===@js($image->id)?'ring-coral':''" @if($hasVariantImages && $image->product_variant_id!==$defaultVariant?->id) style="display:none" @endif><img src="{{ $image->url() }}" alt="{{ $image->alt_text }}" class="h-full w-full object-cover"></button>@endforeach</div>@else<div class="mt-3 min-h-24" aria-hidden="true"></div>@endif
</div>
<div><div class="hidden lg:block"><h1 class="font-display text-5xl">{{ $product->name }}</h1><p class="mt-5 text-lg leading-8 text-muted">{{ $product->short_description }}</p>@if($product->categories->isNotEmpty())<p class="mt-4 text-sm text-muted"><span class="font-semibold text-ink">Categories:</span> @foreach($product->categories as $category)<a class="hover:text-coral hover:underline" href="{{ route('categories.show', $category) }}">{{ $category->name }}</a>@unless($loop->last) <span aria-hidden="true">·</span> @endunless @endforeach</p>@endif</div><p class="mt-6 text-2xl font-bold">Price {{ $product->formattedPrice() }}</p>
<form action="{{ $editing ? route('artwork.upload',$session->public_id) : route('artwork.start',$product->slug) }}" method="POST" enctype="multipart/form-data" @submit="submitting = true">@csrf
<fieldset class="mt-9"><legend class="font-display text-xl">{{ $product->designTemplate ? ($product->preview_configuration['variant_label'] ?? 'Bottle colour') : 'Choose your option' }}</legend><div class="mt-4 {{ $product->designTemplate ? 'bottle-colour-options grid grid-cols-4 gap-2' : 'flex flex-wrap gap-3' }}">@foreach($product->variants as $variant)@php($variantLabel = $product->designTemplate ? str($variant->options['colour'] ?? $variant->name)->title() : $variant->name)@php($variantAvailable = !$product->designTemplate || $variant->hasSingleActiveFulfilmentMapping())<label class="selection-card min-w-0 {{ $variantAvailable ? '' : 'cursor-not-allowed opacity-45' }}" @if(!$variantAvailable) title="This option is not currently available" @endif><input class="sr-only" type="radio" name="variant_id" value="{{ $variant->id }}" x-model="variant" @change="selectVariant(@js($variant->id))" @disabled(!$variantAvailable) required><span>{{ $variantLabel }}<span>{{ $variantAvailable ? $variant->formattedPrice() : 'Unavailable' }}</span></span></label>@endforeach</div></fieldset>
@if($product->artworkStyles->count() > 1)<fieldset x-show="!hasExistingPhoto || removeExistingPhoto" class="mt-10"><legend class="font-display text-xl">Choose your artwork style</legend><div class="mt-4 grid gap-3 sm:grid-cols-2">@foreach($product->artworkStyles as $style)<label class="style-card relative flex min-h-36 items-center gap-3 overflow-hidden {{ $style->is($recommendedStyle) ? 'pt-8' : '' }}">@if($style->is($recommendedStyle))<small class="absolute left-3 top-3 rounded-full bg-emerald-500 px-2.5 py-1 text-[10px] font-bold uppercase leading-none tracking-wide text-white shadow-sm">Recommended</small>@endif<input class="sr-only" type="radio" name="artwork_style_id" value="{{ $style->id }}" x-model="style" required><span class="min-w-0 flex-1 self-center"><span class="flex flex-wrap items-start justify-between gap-1"><strong>{{ $style->slug === 'storybook-cartoon' ? 'Cartoon' : $style->name }}</strong></span><small class="mt-2 block text-muted">{{ $style->description }}</small></span>@if(in_array($style->slug, ['storybook-cartoon', 'hand-drawn']))<span class="flex h-28 w-28 shrink-0 items-center justify-center self-center"><img src="{{ asset('images/artwork-styles/'.$style->slug.'.png') }}" alt="" aria-hidden="true" class="pointer-events-none block h-full w-full object-contain"></span>@endif</label>@endforeach</div></fieldset>@else<input type="hidden" name="artwork_style_id" value="{{ $editing ? $session->artwork_style_id : $product->artworkStyles->first()?->id }}">@endif
@if($product->personalisationFields->isNotEmpty())<fieldset class="mt-10"><legend class="font-display text-xl">A few personal touches</legend><div class="mt-5 space-y-5">@foreach($product->personalisationFields as $field)@php($savedValue=old('personalisation.'.$field->key,$savedPersonalisation->get($field->key)['value']??''))<div><div class="flex items-center justify-between gap-3"><label class="form-label" for="field-{{ $field->id }}">{{ $field->label }} @unless($field->is_required)<span class="font-normal text-muted">(optional)</span>@endunless</label>@if($field->key==='name')<span class="text-xs text-muted" x-text="Math.max(0, {{ $field->validation_rules['max']??12 }} - nameValue.length) + ' characters left'"></span>@endif</div>@switch($field->type->value)@case('textarea')<textarea class="form-control" id="field-{{ $field->id }}" name="personalisation[{{ $field->key }}]" rows="3" @if($field->key==='name') x-model="nameValue" @endif @required($field->is_required) maxlength="{{ $field->validation_rules['max']??500 }}">{{ $savedValue }}</textarea>@break @case('select')<select class="form-control" id="field-{{ $field->id }}" name="personalisation[{{ $field->key }}]" @if($field->key==='name') x-model="nameValue" @endif @required($field->is_required)><option value="">Choose an option</option>@foreach($field->configuration['options']??[] as $option)<option @selected($savedValue===$option)>{{ $option }}</option>@endforeach</select>@break @case('date')<input class="form-control" id="field-{{ $field->id }}" name="personalisation[{{ $field->key }}]" type="date" value="{{ $savedValue }}" @if($field->key==='name') x-model="nameValue" @endif @required($field->is_required)>@break @default<input class="form-control" id="field-{{ $field->id }}" name="personalisation[{{ $field->key }}]" value="{{ $savedValue }}" @if($field->key==='name') x-model="nameValue" @endif @required($field->is_required) maxlength="{{ $field->validation_rules['max']??255 }}">@endswitch</div>@endforeach</div></fieldset>@endif
<fieldset class="mt-10 min-w-0"><legend class="font-display text-xl">Upload photo</legend>@if($editing && $editingPreview)<div x-show="!removeExistingPhoto" class="relative mt-4 inline-block max-w-full"><img src="{{ route('artwork.assets',[$session->public_id,$editingPreview]) }}" alt="Your AI illustration" class="h-[135px] w-auto max-w-full rounded-2xl object-contain shadow"><button type="button" @click="removeExistingPhoto=true;newPhotoSelected=false" class="absolute -right-2 -top-2 flex h-7 w-7 items-center justify-center rounded-full bg-ink text-lg leading-none text-white shadow" aria-label="Remove selected photo">×</button></div>@endif<label x-show="{{ $editing && $editingPreview ? 'removeExistingPhoto' : 'true' }}" class="relative mt-4 flex w-full min-w-0 max-w-full cursor-pointer items-center gap-4 overflow-hidden rounded-2xl border-2 border-dashed border-coral/40 bg-white p-4"><img x-show="uploadPreview" :src="uploadPreview" alt="Selected photo preview" class="h-20 w-20 shrink-0 rounded-xl object-cover" style="display:none"><span class="min-w-0 flex-1"><span class="block font-bold" x-text="newPhotoSelected ? 'Change selected photo' : 'Choose a favourite photo'"></span><span class="mt-1 block text-sm text-muted">JPEG, PNG or WebP · up to 10 MB</span></span><input class="absolute inset-0 h-full w-full cursor-pointer opacity-0" type="file" name="photo" accept="image/jpeg,image/png,image/webp" @change="selectPhoto($event)" @required(!$editing || !$editingPreview)></label></fieldset>
<div class="mt-10 rounded-3xl bg-white p-6 shadow-sm"><button class="button-primary w-full disabled:cursor-not-allowed disabled:opacity-50" type="submit" :disabled="submitting{{ $product->designTemplate ? ' || !variantReady() || !photoReady() || !nameValue.trim()' : '' }}"><span x-show="!submitting">Preview</span><span x-show="submitting">Starting preview…</span></button><p class="mt-3 text-center text-xs text-muted">We’ll prepare your personalised design.</p></div></form>
<div class="mt-10 lg:hidden"><h1 class="font-display text-2xl">{{ $product->name }}</h1><p class="mt-4 leading-7 text-muted">{{ $product->short_description }}</p>@if($product->categories->isNotEmpty())<p class="mt-4 text-sm text-muted"><span class="font-semibold text-ink">Categories:</span> @foreach($product->categories as $category)<a class="hover:text-coral hover:underline" href="{{ route('categories.show', $category) }}">{{ $category->name }}</a>@unless($loop->last) <span aria-hidden="true">·</span> @endunless @endforeach</p>@endif</div>
<div class="mt-10 border-t border-rose/25 pt-8"><h2 class="font-display text-2xl">About your gift</h2><div class="mt-4 whitespace-pre-line leading-7 text-muted">{{ $product->description }}</div></div>
@include('storefront.products._specifications', ['product' => $product])
@include('storefront.products._shipping-returns')
</div></div></section>
@endif
@if($session && !$editing)
@include('storefront.artwork._workspace', ['session' => $session])
@endif
@include('storefront.products._related', ['relatedProducts' => $relatedProducts])
</x-layouts.storefront>
